apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster
  namespace: loadtesting
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 1
  users:
    newgenius:  # database owner
    - superuser
    - createdb
  databases:
    articles_db: newgenius  # dbname: owner
  postgresql:
    version: "15"