version: '3.6'
services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: on-failure:10
    ports:
      - "8256:8200"
    environment:
      VAULT_ADDR: 'http://0.0.0.0:8200'
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-volume:/vault
      - ./vault_config:/vault/config:rw
    # healthcheck:
    #   retries: 5
    command: vault server -config=/vault/config/vault.json
    networks:
      - vault-network

networks:
  vault-network:
    driver: bridge

volumes:
  vault-volume:
    driver: local
