apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: loadtesting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        imagePullPolicy: Always
        image: geek3000/loadtesting-app:latest
        resources:
          limits:
            cpu: "200m"
            memory: "200Mi"
          requests:
            cpu: "100m"
            memory: "100Mi"
        ports:
        - containerPort: 3000
        env:
        - name: USER
          valueFrom:
            configMapKeyRef:
              name: nodejs-config
              key: USER
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: nodejs-config
              key: HOST
        - name: DATABASE
          valueFrom:
            configMapKeyRef:
              name: nodejs-config
              key: DATABASE
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: nodejs-config
              key: DB_PORT
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: newgenius.acid-minimal-cluster.credentials.postgresql.acid.zalan.do
              key: password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-config
  namespace: loadtesting
data:
  USER: newgenius
  HOST: acid-minimal-cluster
  DATABASE: articles_db
  DB_PORT: "5432"

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: loadtesting
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP